version: '3'
services:
  postgres:
    container_name: db-postgres
    image: postgres:13.15
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pg-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
