version: '3'
services:
    minio:
        image: quay.io/minio/minio:latest
        networks:
            - minionetwork
        environment:
            MINIO_ROOT_USER: 'admin'
            MINIO_ROOT_PASSWORD: 'gorangoran'
        env_file:
            - ./development.env
        ports:
            - 9000:7000
            - 9001:7001
        volumes:
            - ./data:/data

        command: server /data --console-address ":9001"

networks:
    minionetwork:
        driver: bridge
