name: CI

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v2
              with:
                  version: 10

            - run: pnpm install --no-frozen-lockfile
            - run: pnpm nx affected --base=origin/main -t lint

    build:
        needs: ['lint']
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2
              with:
                  version: 10
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm nx affected --base=origin/main -t build

    test:
        needs: ['build']
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2
              with:
                  version: 10
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm nx affected --base=origin/main -t test

    e2e:
        needs: ['build', 'test']
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v2
              with:
                  version: 10
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm nx affected -t e2e
