name: CI

on:
    push:
        branches: [main]
    pull_request:

permissions:
    actions: read
    contents: read

jobs:
    lint:
        name: Lint (affected)
        uses: ./.github/workflows/nx-affected-template.yml
        with:
            nx_target: lint
        secrets: inherit

    build:
        name: Build (affected)
        needs: [lint]
        uses: ./.github/workflows/nx-affected-template.yml
        with:
            nx_target: build
        secrets: inherit

    test:
        name: Test (affected)
        needs: [build]
        uses: ./.github/workflows/nx-affected-template.yml
        with:
            nx_target: test
        secrets: inherit
