name: Nx Affected Template

on:
    workflow_call:
        inputs:
            nx_target:
                required: true
                type: string

permissions:
    actions: read
    contents: read

jobs:
    run:
        runs-on: ubuntu-latest
        environment: Preview
        env:
            NODE_VERSION: '20'
            API_BASE_URL: ${{ vars.API_BASE_URL }}
            JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
            JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
            SECURITY_EXPIRES_IN: ${{ vars.SECURITY_EXPIRES_IN }}
            SECURITY_REFRESH_IN: ${{ vars.SECURITY_REFRESH_IN }}
            SECURITY_BCRYPT_SALT: ${{ vars.SECURITY_BCRYPT_SALT }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: https://registry.npmjs.org
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run affected target
              run: pnpm nx affected --base=origin/main -t ${{ inputs.nx_target }}
