name: Validate Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]
  pull_request:

jobs:
  conventional_commit:
    name: Conventional Commit Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: ${{ inputs.scopes }}
          requireScope: true
          types: |
            build
            chore
            ci
            docs
            feat
            improve
            fix
            merge
            perf
            refactor
            refact
            revert
            style
            test
            wip
          ignoreLabels: |
            autorelease: pending
